chalk_root/main/urls.py
from django.urls import path

from chalk_root.main.views import *

app_name = "main"
urlpatterns = [
    path("", HomePageView.as_view(), name='HomePageView'),
    path("school/<school_id>", SchoolView.as_view(), name='SchoolView'),
    path("add/school/", SchoolCreateView.as_view(), name='create_school'),
    path("list/", search_view, name='SchoolListView'),
    path("compare/", CompareSchoolView.as_view(), name='compare'),
]

chalk_root/users/urls.py
from django.urls import path

from chalk_root.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", include("chalk_root.main.urls", namespace="main")),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("chalk_root.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

chalk_root/main/models.py
from django.db import models

from cloudinary.models import CloudinaryField

from chalk_root.users.models import User

app_name = "main"

class UserType(models.Model):
	"""
		UserType: Used to store the type of user Ex: Student, Principal, Professor etc.
	"""
	name = models.CharField("Type of User", max_length=50)

	def __str__(self):
		return self.name


class UserInfo(models.Model):
	"""
	Description: Preferences and information about the user
	"""
	user = models.ForeignKey('users.User', blank=True, null=True, on_delete=models.CASCADE)
	user_type = models.ForeignKey("UserType", blank=True, null=True, on_delete=models.CASCADE)
	school_admin = models.ForeignKey('School', blank=True, null=True, related_name='school_admin', on_delete=models.CASCADE)
	employment_details = models.TextField(blank=True, null=True)
	phone = models.CharField(max_length=20, blank=True, null=True)
	address = models.TextField(blank=True, null=True)
	photo = models.TextField(blank=True, null=True)
	child_school = models.ForeignKey('School', blank=True, null=True, related_name='child_school', on_delete=models.CASCADE)
	facility_preferred = models.ManyToManyField('School')
	

	class Meta:
		pass

class School(models.Model):
	"""
	School: Strores all details about the school
	"""
	sid = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=30, blank=True, null=True)
	category =  models.ForeignKey('Category', blank=True, null=True, on_delete=models.CASCADE)
	address_line1 = models.CharField(max_length=30, blank=True, null=True)
	address_line2 = models.CharField(max_length=30, blank=True, null=True)
	area = models.CharField(max_length=30, blank=True, null=True)
	city = models.CharField(max_length=30, blank=True, null=True)
	state = models.CharField(max_length=30, blank=True, null=True)
	description = models.TextField(blank=True, null=True)
	facilities = models.CharField(max_length=100 ,blank=True, null=True)
	contact_number = models.CharField(max_length=20,blank=True, null=True)
	website = models.CharField(max_length=30, blank=True, null=True)
	photos = CloudinaryField('image',blank=True, null=True)
	admission_info = models.TextField(blank=True, null=True)
	overall_rating = models.FloatField(blank=True, null=True)
	board = models.ForeignKey('Board', blank=True, null=True, on_delete=models.CASCADE)
	added_by = models.ForeignKey("users.User", blank=True, null=True, related_name='school_creator', on_delete=models.CASCADE)
	def __str__(self):
		return self.name


class Board(models.Model):
	"""
	Facilities: Stores individual facility provided info
	"""
	name = models.CharField(max_length=10, blank=True, null=True)

	def __str__(self):
		return self.name


class Reviews(models.Model):
	"""
	Reviews: Stores reviews for each school
	"""
	school = models.ForeignKey('School', blank=True, null=True, on_delete=models.CASCADE)
	parent = models.ForeignKey('users.User', blank=True, null=True, on_delete=models.CASCADE)
	review_content = models.TextField(blank=True, null=True)
	rating = models.CharField(max_length=10)

	def __str__(self):
		return parent.name

class Category(models.Model):
	"""
	Category: Stores the type of school, primary, secondary,etc.
	"""
	name = models.CharField(max_length=10, blank=True, null=True)

	def __str__(self):
		return self.name
	

chalk_root/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

app_name = "users"

class User(AbstractUser):

	# First Name and Last Name do not cover name patterns
	# around the globe.
	name = CharField(_("Name of User"), blank=True, max_length=255)
	

	def get_absolute_url(self):
		return reverse("users:detail", kwargs={"username": self.username})

chalk_root/main/forms.py
from django import forms

from .models import *
from django.contrib.auth import get_user_model

class SchoolCreateForm(forms.ModelForm):
	class Meta:
		User = get_user_model()
		model = School
		exclude = ('added_by', 'overall_rating')

class SearchForm(forms.ModelForm):
	class Meta:
		model = School
		exclude = ('added_by','sid','contact_number','website','photos','admission_info',)

chalk_root/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

chalk_root/main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, View, CreateView
from django.views.generic.list import ListView

from django.urls import reverse_lazy

from django.contrib.auth import get_user_model
from django.http import HttpResponse, HttpResponseRedirect

from .models import *
from .forms import *
# Create your views here.

class HomePageView(TemplateView):
	template_name = "index.html"

	def get_context_data(self, *args, **kwargs):
		context = super(HomePageView, self).get_context_data(**kwargs)
		board = Board.objects.all()
		types = Category.objects.all()
		context['board_list'] =  board
		context['type_list'] =  types
		return context


class SchoolView(TemplateView):
	template_name = "detail.html"

	def get_context_data(self, *args, **kwargs):
		context = super(SchoolView, self).get_context_data(**kwargs)
		school_id = kwargs.get('school_id', None)
		school_details = School.objects.get(sid=school_id)
		context['school'] =  school_details
		return context


class SchoolCreateView(CreateView):
	model = School
	template_name = "school_create.html"

	success_url = reverse_lazy("school")
	error_url = reverse_lazy('school_create')
	form_class = SchoolCreateForm

	def get_context_data(self, *args, **kwargs):
		context = super(SchoolCreateView, self).get_context_data(*args, **kwargs)
		return context
	
	def form_valid(self, form):
		create = form.save(commit=False)
		create.added_by = self.request.user
		create.save()
		return HttpResponseRedirect('/list/')
	
	def form_invalid(self,form):
		print(form.errors)
		return HttpResponseRedirect('/add/school')


class SchoolListView(ListView):
	model = School
	template_name = "school_list.html"

	def get_context_data(self, **kwargs):
		print('rating list')
		context = super(SchoolListView, self).get_context_data(**kwargs)
		school_list = School.objects.all()
		rating_list = []
		for school in school_list:
			rating_list.append(school.overall_rating)
		print('-----')
		print(rating_list)
		context['ratings'] = list(set(rating_list))
		return context

def search_view(request):
	context = {}
	schools = School.objects.all()
	form = SearchForm(request.GET)
	if form.is_valid():
		if form.cleaned_data["city"] and form.cleaned_data["name"] and form.cleaned_data["board"] and form.cleaned_data["type"]:
			schools = schools.filter(city__icontains=form.cleaned_data["city"], 
				name__icontains=form.cleaned_data["name"], 
				board__name__icontains=form.cleaned_data["board"],
				category__name__icontains=form.cleaned_data["type"])
		elif form.cleaned_data["city"] and form.cleaned_data["name"] and form.cleaned_data["board"] and not form.cleaned_data["type"]:
			schools = schools.filter(city__icontains=form.cleaned_data["city"], 
				name__icontains=form.cleaned_data["name"], 
				board__name__icontains=form.cleaned_data["board"])
		elif form.cleaned_data["city"] and form.cleaned_data["name"] and not form.cleaned_data["board"] and not form.cleaned_data["type"]:
			schools = schools.filter(city__icontains=form.cleaned_data["city"], 
				name__icontains=form.cleaned_data["name"],)
		else:
			pass
	rating_list = []
	for school in schools:
		rating_list.append(school.overall_rating)
	context['ratings'] = list(set(rating_list))
	context["form"] = form
	context['object_list'] = schools
	context['board'] = Board.objects.all()
	return render(request, "school_list.html",context)


class CompareSchoolView(ListView):
	model = School
	template_name = "compare.html"

	def get_context_data(self, *args, **kwargs):
		context = super(CompareSchoolView, self).get_context_data(**kwargs)
		return context

chalk_root/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

chalk_root/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

chalk_root/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Chalk Root{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap 4.1.1 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/">Chalk Root</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Required by Bootstrap v4.1.1 -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

chalk_root/templates/school_create.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js"> <!--<![endif]-->
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="description" content="Bingo One page parallax responsive HTML Template ">

  <title>Add School</title>

<!-- Mobile Specific Meta
  ================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  	<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/fontastic.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="vendor/@fancyapps/fancybox/jquery.fancybox.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/tagify.css' %}">
</head>

<body id="body">

 <!--
  Start Preloader
  ==================================== -->
  <div id="preloader">
    <div class="preloader">
      <div class="sk-circle1 sk-child"></div>
      <div class="sk-circle2 sk-child"></div>
      <div class="sk-circle3 sk-child"></div>
      <div class="sk-circle4 sk-child"></div>
      <div class="sk-circle5 sk-child"></div>
      <div class="sk-circle6 sk-child"></div>
      <div class="sk-circle7 sk-child"></div>
      <div class="sk-circle8 sk-child"></div>
      <div class="sk-circle9 sk-child"></div>
      <div class="sk-circle10 sk-child"></div>
      <div class="sk-circle11 sk-child"></div>
      <div class="sk-circle12 sk-child"></div>
    </div>
  </div> 
 {% include 'partials/nav_primary.html' %}
<!-- Srart Contact Us
		=========================================== -->		
	<section class="contact-us section bg-gray" id="contact">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="title text-center">
						<h2>Add School.</h2>
						<span class="border"></span>
						<p>PLease enter the below details to add a new school</p>
					</div>
				</div>
			</div>
			<div class="row">
				<!-- Contact Form -->
				<div class="contact-form col-12 col-md-6  mx-auto" >
					<form id="contact-form" method="post" role="form">{% csrf_token %}
					
						<div class="form-group">
							{% render_field form.sid class="form-control" placeholder="School ID" %}
						</div>
						<div class="form-group">
							{% render_field form.name class="form-control" placeholder="School Name" %}
						</div>
						<div class="form-group">
							{% render_field form.address_line1 class="form-control" placeholder="School Address Line 1" %}
						</div>
						<div class="form-group">
							{% render_field form.address_line2 class="form-control" placeholder="School Address Line 2" %}
						</div>
						<div class="form-group">
							{% render_field form.area class="form-control" placeholder="Area" %}
						</div>
						<div class="form-group">
							{% render_field form.city class="form-control" placeholder="City" %}
						</div>
						<div class="form-group">
							{% render_field form.state class="form-control" placeholder="State" %}
						</div>
						<div class="form-group">
							{% render_field form.description class="form-control" placeholder="Description" %}
						</div>
						<div class="form-group">
							<input name='facilities' class='form-control' id="id_facilities" placeholder='Facilities' autofocus>
						</div>
						<div class="form-group">
							{% render_field form.contact_number class="form-control" placeholder="Contact Number" %}
						</div>
						<div class="form-group">
							{% render_field form.website class="form-control" placeholder="Website" %}
						</div>
						<div class="form-group">
							{% render_field form.photos class="form-control" placeholder="Photos" %}
						</div>
						<div class="form-group">
							{% render_field form.admission_info class="form-control" placeholder="Admission Info" %}
						</div>
						<div class="form-group">
							{% render_field form.academic_record class="form-control" placeholder="Academic Record" %}
						</div>
						<div id="mail-success" class="success">
							Thank you. The Mailman is on His Way :)
						</div>
						
						<div id="mail-fail" class="error">
							Sorry, don't know what happened. Try later :(
						</div>
						
						<div id="cf-submit">
							<input type="submit" id="contact-submit" class="btn btn-transparent" value="Submit">
						</div>						
						
					</form>
				</div>
				<!-- ./End Contact Form -->
			</div> <!-- end row -->
			
		</div> <!-- end container -->
	</section> <!-- end section -->

{% include 'partials/footer.html' %}
    
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/tagify.polyfills.js' %}"></script>
    <script src="{% static 'js/tagify.js' %}"></script>
    <script src="{% static 'js/jQuery.tagify.js' %}"></script>

<script data-name="basic">
(function(){

var input = document.querySelector('input[name=facilities]'),
    tagify = new Tagify(input, {
        whitelist : [
        'Playground', 'Canteen', 'Transport',
        ],
        blacklist : [""]
    });

// "remove all tags" button event listener
document.querySelector('.tags--removeAllBtn')
    .addEventListener('click', tagify.removeAllTags.bind(tagify))

// Chainable event listeners
tagify.on('add', onAddTag)
      .on('remove', onRemoveTag)
      .on('invalid', onInvalidTag);

// tag added callback
function onAddTag(e){
    console.log(e, e.detail);
    console.log( tagify.DOM.originalInput.value )
    tagify.off('add', onAddTag) // exmaple of removing a custom Tagify event
}

// tag remvoed callback
function onRemoveTag(e){
    console.log(e, e.detail);
}

// invalid tag added callback
function onInvalidTag(e){
    console.log(e, e.detail);
}

})()
</script>
  </body>
  </html>